name: tpay_flutter
description: Unofficial Tpay Flutter plugin
version: 0.0.5
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: mobi.qrtag.tpay_flutter
        pluginClass: TpayFlutterPlugin
      ios:
        pluginClass: TpayFlutterPlugin
